# generated by datamodel-codegen:
#   filename:  swagger.json
#   timestamp: 2024-08-16T18:54:32+00:00

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
from typing import Any


@dataclass
class PingRequestSchema:
    pass


@dataclass
class PingResponseSchema:
    ping: str | None = None


@dataclass
class CreateSourceRequestSchema:
    title: str | None = None
    authors: list[str] | None = None
    year: int | None = None


@dataclass
class CreateSourceResponseSchema:
    code: str


@dataclass
class GetSourceRequestSchema:
    id: int


@dataclass
class GetSourceResponseSchema:
    code: str | None = None
    title: str | None = None
    authors: list[str] | None = None
    year: int | None = None


@dataclass
class StartTaskRequestSchema:
    task_name: str
    payload: dict[str, Any] | None = None


@dataclass
class StartTaskResponseSchema:
    id: int | None = None


@dataclass
class GetTaskInfoRequestSchema:
    task_id: int


@dataclass
class GetTaskInfoResponseSchema:
    id: int | None = None
    task_name: str | None = None
    status: str | None = None
    payload: dict[str, Any] | None = None
    start_time: str | None = None
    end_time: str | None = None
    message: dict[str, Any] | None = None


class DataType(Enum):
    str = "str"
    string = "string"
    int = "int"
    integer = "integer"
    float = "float"
    double = "double"


@dataclass
class ColumnDescription:
    name: str
    data_type: DataType
    unit: str | None = None
    ucd: str | None = None
    description: str | None = ""


class Datatype(Enum):
    regular = "regular"
    reprocessing = "reprocessing"
    preliminary = "preliminary"
    compilation = "compilation"


@dataclass
class CreateTableRequestSchema:
    table_name: str
    columns: list[ColumnDescription]
    bibcode: str
    datatype: Datatype | None = Datatype.regular
    description: str | None = ""


@dataclass
class CreateTableResponseSchema:
    id: int


@dataclass
class AddDataRequestSchema:
    table_id: int
    data: list[dict[str, Any]]


@dataclass
class AddDataResponseSchema:
    pass


@dataclass
class LoginRequestSchema:
    username: str
    password: str


@dataclass
class LoginResponseSchema:
    token: str | None = None
