# generated by datamodel-codegen:
#   filename:  swagger.json
#   timestamp: 2025-06-07T08:18:05+00:00

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
from typing import Any


class PageSize(Enum):
    integer_10 = 10
    integer_25 = 25
    integer_50 = 50
    integer_100 = 100


@dataclass
class QuerySimpleRequestSchema:
    pgcs: list[int] | None = None
    ra: float | None = None
    dec: float | None = None
    radius: float | None = None
    name: str | None = None
    cz: float | None = None
    cz_err_percent: float | None = None
    page_size: PageSize | None = PageSize.integer_25
    page: int | None = 0


@dataclass
class PGCObject:
    pgc: int | None = None
    catalogs: dict[str, dict[str, Any]] | None = None


@dataclass
class QuerySimpleResponseSchema:
    objects: list[PGCObject] | None = None


@dataclass
class QueryRequestSchema:
    q: str | None = None
    page_size: PageSize | None = PageSize.integer_25
    page: int | None = 0


@dataclass
class QueryResponseSchema:
    objects: list[PGCObject] | None = None


class PageSize2(Enum):
    integer_10 = 10
    integer_25 = 25
    integer_50 = 50
    integer_100 = 100
    integer_1000 = 1000
    integer_10000 = 10000
    integer_100000 = 100000


@dataclass
class FITSRequestSchema:
    pgcs: list[int] | None = None
    ra: float | None = None
    dec: float | None = None
    radius: float | None = None
    name: str | None = None
    cz: float | None = None
    cz_err_percent: float | None = None
    page_size: PageSize2 | None = PageSize2.integer_25
    page: int | None = 0


@dataclass
class Schema:
    pass
