name: Test and build

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10' 
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Check that code is formatted correctly
        run: |
          make check-format
      - name: Check the code for smells and potential bugs
        run: |
          make check-lint
      - name: Build Package
        run: make build